<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>gov.llnl.wintap.api</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyTitle>WintapAPI</AssemblyTitle>
    <Company>LLNL</Company>
    <Product>WintapAPI</Product>
    <Copyright>Copyright 2025</Copyright>
    <AssemblyVersion>7.0.0.0</AssemblyVersion>
    <FileVersion>7.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>