<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>nesper_repro</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NEsper.Compiler" Version="8.9.0" />
    <PackageReference Include="NEsper.Runtime" Version="8.9.0" />
    <PackageReference Include="NEsper.Compat" Version="8.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../shared/WintapAPI/WintapAPI.csproj" />
  </ItemGroup>

</Project>
